import type { Match, News, Player } from "@/lib/types";

export const data: Player[] = [
  {
    id: 101,
    name: "Drew Harrison",
    class: "Senior",
    wins: 22,
    losses: 5,
    height: "6'0\"",
    playing_style: "Aggressive Baseliner",
    yearsOnVarsity: 4,
    isVarsity: true,
    hometown: "Lawrence, KS",
    bio: "A four-year varsity player known for his powerful forehand and leadership on the court.",
    gender: "Boy",
    profileImageUrl: "/images/players/drew_harrison.jpg",
  },
  {
    id: 102,
    name: "Lawrence Dao",
    class: "Sophomore",
    wins: 18,
    losses: 8,
    height: "5'9\"",
    playing_style: "Counter-Puncher",
    yearsOnVarsity: 3,
    isVarsity: true,
    hometown: "Lawrence, KS",
    bio: "Known for his incredible speed and agility, making him a formidable defensive player.",
    gender: "Boy",
    profileImageUrl: "/images/players/lawrence_dao.jpg",
  },
  {
    id: 103,
    name: "Connor Coons",
    class: "Senior",
    wins: 19,
    losses: 7,
    height: "5'11\"",
    playing_style: "Serve and Volley",
    yearsOnVarsity: 4,
    isVarsity: true,
    hometown: "Lawrence, KS",
    bio: "Team captain and a doubles specialist with a strategic net game.",
    gender: "Boy",
    profileImageUrl: "/images/players/connor_coons.jpg",
  },
  {
    id: 104,
    name: "Jacob Wang",
    class: "Senior",
    wins: 19,
    losses: 7,
    height: "6'1\"",
    playing_style: "All-Court Player",
    yearsOnVarsity: 2,
    isVarsity: true,
    hometown: "Lawrence, KS",
    bio: "Praised for his consistent serves and strong communication with his partner.",
    gender: "Boy",
    profileImageUrl: "/images/players/jacob_wang.jpg",
  },
  {
    id: 105,
    name: "Galeno Wills",
    class: "Senior",
    wins: 15,
    losses: 10,
    height: "5'9\"",
    playing_style: "Doubles Strategist",
    yearsOnVarsity: 1,
    isVarsity: true,
    hometown: "Lawrence, KS",
    bio: "A quick player who excels at the net and has great volleying skills.",
    gender: "Boy",
    profileImageUrl: "/images/players/galeno_wills.jpg",
  },
];

export const matches: Match[] = [
  {
    date: "TUE APR 8 2025",
    time: "4:00 PM",
    locationType: "Away",
    teamLevel: "Boys Varsity",
    opponent: "Shawnee Mission East High School",
    venue: "Shawnee Mission East HS (Prairie Village, KS)",
  },
  {
    date: "THU APR 10 2025",
    time: "3:30 PM",
    locationType: "Home",
    teamLevel: "Boys Varsity",
    opponent: "Olathe North High School",
    venue: "Lawrence Free State High School (Lawrence, KS)",
  },
  {
    date: "SAT APR 12 2025",
    time: "9:00 AM",
    locationType: "Away",
    teamLevel: "Boys Varsity",
    opponent: "Multiple Schools",
    venue: "College Boulevard Activity Center (Olathe, KS)",
  },
  {
    date: "MON APR 14 2025",
    time: "4:00 PM",
    locationType: "Home",
    teamLevel: "Boys Junior Varsity",
    opponent: "Gardner Edgerton High School",
    venue: "Lawrence Free State High School (Lawrence, KS)",
  },
];

export const news: News[] = [
  {
    id: "blog-1",
    thumbnailUrl: "/images/blog/tennis-spotlight.jpg",
    readTimeMinutes: 4,
    title: "Meet the Lawrence High Tennis Team: Player Spotlights",
    content:
      "Tennis is more than just a game at Lawrence High. It is a community, a passion, and a journey of growth. The Lawrence High Tennis Team is made up of dedicated student-athletes who balance academics, training, and competition with remarkable skill. In this series, we'll introduce you to the players who make our team special. From the seasoned seniors leading the charge to the promising freshmen just beginning their high school careers, each player brings a unique story and a powerful drive to succeed. Join us as we shine a spotlight on their hard work, their goals, and what being a part of the team means to them.",
    views: 3,
    comments: 0,
    publishDate: "1 day ago",
  },
  {
    id: "blog-2",
    thumbnailUrl: "/images/blog/training-drills.jpg",
    readTimeMinutes: 7,
    title: "Top 5 Drills to Improve Your Serve Speed",
    content:
      "A powerful serve can change the game, putting pressure on your opponent from the very first shot. But how do you add more pace without sacrificing control? Our coaching staff has compiled their top five drills designed to improve your kinetic chain, racket head speed, and overall serving mechanics. We'll break down each drill, from the 'Throw the Ball' exercise to build arm speed, to the 'Pinpoint Stance' drill for better balance and power transfer. Whether you're a beginner looking to build a solid foundation or an advanced player hoping to add a few more miles per hour to your serve, these proven techniques will help you dominate the court.",
    views: 128,
    comments: 5,
    publishDate: "3 days ago",
  },
  {
    id: "blog-3",
    thumbnailUrl: "/images/blog/season-recap.jpg",
    readTimeMinutes: 6,
    title: "Varsity Boys' Season Recap: A Year of Growth and Triumphs",
    content:
      "From intense practices in the late summer sun to nail-biting matches under the lights, the Varsity Boys' tennis team had an unforgettable season. This year was a testament to resilience and teamwork. We look back at the key moments that defined our journey, including the thrilling victory over our cross-town rivals and our strong showing at the regional tournament. We'll also highlight some standout performances from players who stepped up when it mattered most. This season was filled with personal bests, hard-fought battles, and memories that will last a lifetime. Thank you to all the players, coaches, and families who made it a success.",
    views: 256,
    comments: 12,
    publishDate: "1 week ago",
  },
  {
    id: "blog-4",
    thumbnailUrl: "/images/blog/nutrition-tips.jpg",
    readTimeMinutes: 3,
    title: "Fueling Your Game: Nutrition Tips for Young Athletes",
    content:
      "What you eat matters as much as how you train. For a young tennis player, proper nutrition is the fuel that powers performance and aids recovery. It's not just about what you eat right before a match, but about building consistent, healthy habits. In this post, we'll cover the basics of sports nutrition, including the importance of carbohydrates for energy, protein for muscle repair, and hydration for endurance. We'll also share simple, practical tips for pre-match meals and post-match recovery snacks to help you stay at the top of your game, both on and off the court.",
    views: 78,
    comments: 2,
    publishDate: "2 weeks ago",
  },
];
